# This workflow builds and tests the Node.js project and includes linting for code quality
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x] # Testing across different Node.js versions
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js environment
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache dependencies to speed up subsequent builds

    # Step 3: Install dependencies
    - name: Install Dependencies
      run: npm ci

    # Step 4: Lint the codebase for issues
    - name: Run Linter
      run: npm run lint

    # Step 5: Build the application (if applicable)
    - name: Build Application
      run: npm run build --if-present

    # Step 6: Run tests
    - name: Run Tests
      run: npm test

    # Step 7: Upload build artifacts (optional)
    # Uncomment if the build step generates files you'd like to keep
    # - name: Upload Build Artifacts
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: build-artifacts
    #     path: ./build
